import Head from "next/head"
import Posts from "./posts"

const text =
  "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."

const posts = [
  {
    id: "234",
    title: "ITS A ME MARIO",
    date: new Date(),
    text: text,
    postedByName: "Bela",
    postedByLink: "https://tulipsarebetter.com/user/bela2",
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Echo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#00BFB2] to-[#f0f3bd]">
        <h1 className="mt-8 font-mono text-7xl subpixel-antialiased drop-shadow-lg">
          Echo
        </h1>
        <Posts posts={[...posts, ...posts, ...posts, ...posts, ...posts]} />
      </main>
    </>
  )
}
