import Head from "next/head"
import Posts from "./components/posts"
import { getEchos } from "~/data/echos"

export default async function Home() {
  const echos = await getEchos()

  const { posts } = echos

  return (
    <>
      <Head>
        <title>Echo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Posts posts={[...posts, ...posts, ...posts, ...posts, ...posts]} />
    </>
  )
}
