import Head from "next/head"
import Container from "~/app/components/container"

async function getData(id: string) {
  // const res = await fetch(`https://echo.com/user/${id}`)
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.
  // if (!res.ok) {
  // This will activate the closest `error.js` Error Boundary
  // throw new Error("Failed to fetch data")
  // }
  // return res.json()
}

export default async function Submit({ params }: { params: { id: string } }) {
  async function createEcho(formData: FormData) {
    "use server"

    const rawFormData = {
      text: formData.get("text"),
    }

    // mutate data
    // revalidate cache
    console.log("here", formData.get("text"))
  }

  const { id } = params
  // const data = await getData(id)

  return (
    <>
      <Head>
        <title>Echo - Echo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <form action={createEcho} className="flex flex-col gap-y-2">
          <label>Send an echo to...</label>
          <textarea name="text" autoFocus className="outline-none" />
          <button
            type="submit"
            className="mx-auto mt-4 w-40 bg-teal-400 py-2 text-white hover:bg-teal-600"
          >
            Submit
          </button>
        </form>
      </Container>
    </>
  )
}
